FROM debian:latest

MAINTAINER wzwolfx wzwolfx@gmail.com

RUN apt update -y
RUN apt upgrade -y
RUN apt install git -y
RUN apt install nano -y
RUN git clone https://github.com/wzwolf/emailtemplatenodejs.git

EXPOSE 3000
EXPOSE 3001
